version: "3.9"

services:
  tg-bot:
    image: ghcr.io/shama-chan/telegram_bot_k:sha-dd62aa2aad06eaa89f7863e8a4aaec6bbbcb1b37
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
